### ISSUE TITLE
Wire speech_to_text_generation_service (and speech_to_text_request_service or whatever is used for signalling between SDR and cloud speech_to_text_generation_service deployment) up to workflows.

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/common-accessioning#1363]
see [workflow diagram](https://docs.google.com/drawings/d/1Z6KFhS77VQ2jZhbhjibh59nU0w5-F7OWMjVymPQ4NHQ/edit)

this is a meta ticket for tracking:
- [x] sul-dlss/common-accessioning#1350
- ~~sul-dlss/common-accessioning#1364~~ (not really part of getting the workflow working afterall, prioritized separately)
- [x] sul-dlss/common-accessioning#1356
- [x] sul-dlss/common-accessioning#1358
- [x] sul-dlss/common-accessioning#1359
- [x] sul-dlss/common-accessioning#1360
- [x] sul-dlss/common-accessioning#1361
- [x] sul-dlss/common-accessioning#1362

this can be closed once it's confirmed that all of the above are done, and that no further adjustment to the expected set of workflow steps is needed.  it might be a good idea to grep for `TODO` in that workflow, and to ticket anything that is otherwise not ticketed or implemented (also nice to give a link in any remaining TODO comments to the corresponding github issues).

**Comment by jmartin-sul** [comment]
seems like we have the workflow working end to end, and the stuff around getting the container running in ECS, and finishing off puppet and cap stuff for the watcher, is all ticketed and prioritized on its own
