### ISSUE TITLE
when available, upgrade preservation-client

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/common-accessioning#502]
once https://github.com/sul-dlss/preservation-client/pull/29 is merged and a new version has been cut:
- [x] update the preservation-client gem (PR #503)
- [x] add an example token setting in settings.yml  (PR #503)
- [x] update the [`Preservation::Client.configure` call](https://github.com/sul-dlss/common-accessioning/blob/9d0838988de0636036cc8c042fae60134bffcf2c/config/boot.rb#L57) to use the new setting (PR #503)
- [x] mint real tokens on stage and prod pres cat servers, and add those token values as corresponding overrides in the stage and prod shared configs settings (PRs sul-dlss/shared_configs/pull/1171, sul-dlss/shared_configs/pull/1175)

**Comment by jmartin-sul** [comment]
see also https://github.com/sul-dlss/preservation_catalog/pull/1306 and https://github.com/sul-dlss/preservation_catalog/issues/1298
