### ISSUE TITLE
DOR, Purl, Hydrus Mount Migrations Checklist

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/common-accessioning#702]
We need to shut down services to allow for the /dor, /purl and /hydrus/data-files data mounts to be migrated so that nothing writes to these mounts during the migration. We don't anticipate Fedora having to go down.  This is the order of operations for how things will be shut down.

Mounts being migrated:

```
sf4-webapp:/vol/sul_purl_prod                           150G  101G   50G  68% /purl
sf3-webapp:/vol/sul_lyberservices_prod_01                21T  5.8T   16T  28% /dor
sf3-webapp:/vol/hydrus_files_prod                       7.0T  5.3T  1.8T  75% /data/hydrus-files
```

Services impacted: https://github.com/sul-dlss/puppet/search?q=sul_lyberservices_prod_01

## Overview
We need to ensure these services are not utilized:
- robots
	- common accessioning robots
	- preservation robots
	- gis robots
	- was robots
- google books
- preassembly
- goobi
- argo
- hydrus

For the robots, google books and hydrus, we will make an effort to stop them as shown in the To Do steps below.  For the other services (e.g. goobi, argo, pre-assembly), we will rely on communication from the SDR Service Manager and compliance from staff.

## Shutdown Steps:
- [x] Google Books: disable google books via the UI: https://sul-gbooks-prod.stanford.edu/features
- [x] Preservation Robots (preservation_robots): stop the workers  (see below)
- [x] Common Accessioning Robots (common-accessioning): stop the workers  (see below)
- [x] WAS Robots (was_robot_suite): stop the workers  (see below)
- [x] GIS Robots (gis-robot-suite): stop the workers  (see below)
- [x] Hydrus : put up a maintenance page  (see below)

## Restart Steps:
- [ ] Google Books: enable google books via the UI: https://sul-gbooks-prod.stanford.edu/features
- [x] Preservation Robots (preservation_robots): start the workers   (see below)
- [x] Common Accessioning Robots (common-accessioning): start the workers  (see below)
- [x] WAS Robots (was_robot_suite): start the workers  (see below)
- [x] GIS Robots (gis-robot-suite): start the workers  (see below)
- [x] Hydrus : restore the app  (see below)

## Cleanup:

We should go back and cleanup any DevOpsDocs to indicate how to actually stop the workers if `cap resque:pool:stop` indeed does not work now that we are using hot swap (e.g. https://github.com/sul-dlss/DevOpsDocs/blob/master/projects/common-accessioning/common-accessioning-ops-concerns.md)

## Hydrus Maintenance

From the hydrus codebase on your laptop, to stop:

```
git fetch
cap prod deploy # select the maintenance-page branch
```

From the hydrus codebase on your laptop, to start:

```
git fetch
cap prod deploy # select the master branch
```

## Stopping robot workers

NOTE: THE ORIGINAL PLAN TO STOP WORKERS WITH `bundle exec cap prod resque:pool:stop` DID NOT WORK, POSSIBLY DUE TO HOT_SWAP.  

From Tony Z:

```
I think that what happens is on a deployment, capistrano uses hot_swap. hot_swap uses a lock files instead of pid files to manage pools. The stop command depends on a pid file, doesn't care about lock files, and since a pid file isn't there, resque-pool thinks there's no pool to stop.
```

Instead I ended up creating a branch of each project called `no-workers` and setting the worker counts to 0 in the `config/resque-pool.yml` file, and then deploying the `no-workers` branch for these projects:

```
cap prod deploy # select no-workers branch
```

Projects:
* common-accessioning
* preservation_robots
* was_robot_suite
* gis-robot-suite

I then verified workers were stopped here: https://robot-console-prod.stanford.edu/workers

(Original plan to stop workers included details from here: https://github.com/sul-dlss/preservation_catalog/issues/1559#issuecomment-635133260)

## Starting robot workers

Since the original plan to stop the workers did not work (see above), instead of using the cap command to restart resque, starting them just involves re-deploying each project using the master branch to get the worker counts back where they should be.

```
cap prod deploy # select master branch
```

Projects:
* common-accessioning
* preservation_robots
* was_robot_suite
* gis-robot-suite

Verify workers are started here: https://robot-console-prod.stanford.edu/workers
You can also check on the each server and look for processes that include `resque` (e.g. `ps -ef | grep resque`)

## Queue dashboards:
  - robots
    - https://robot-console-prod.stanford.edu/overview
      - https://robot-console-prod.stanford.edu/failed
    - https://argo.stanford.edu/report/workflow_grid
  - pre-assembly
    - https://sul-preassembly-prod.stanford.edu/resque/overview
  - preservation
    - https://preservation-catalog-prod-01.stanford.edu/resque/overview
      - https://preservation-catalog-prod-01.stanford.edu/resque/failed
  - web-registrar-app
    - https://was-registrar-app.stanford.edu/queues
  - dor-services-app sidekiq (for jobs run by workers in other threads):
    - https://dor-services-prod.stanford.edu/queues/
  - google books
    - https://sul-gbooks-prod.stanford.edu/queues
  - sdr-api
    - https://sdr-api-prod.stanford.edu/queues
  - techmd service
    - https://dor-techmd-prod.stanford.edu/queues

**Comment by andrewjbtw** [comment]
We'll also need to hold ETDs back from accessioning, but ETD has its own storage space, right? So potentially someone could do everything to file while the migration is happening, but the deposit wouldn't be sent over to SDR until after the migration. I'm not sure how ETDs work now, pre-accessioning. Do they use the SDR API?
